import type { Metadata } from 'next'
import Link from 'next/link'

import { playfair_display, noto_serif_KR } from '@/font'

import '../common_style/globals.css'
import '../common_style/common.scss'

export const metadata: Metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
        <html>
            <body>
                    <header className={`main_banner ${playfair_display.className}`}>
                        <h1>
                            <Link href={'/'}>My Gam-Sung Blog</Link>
                        </h1>
                    </header>
                    <section className={`main_section ${noto_serif_KR.className}`}>
                        {children}
                    </section>
            </body>
        </html>
    )
}
